server {
    listen 443 ssl;
    listen [::]:443 ssl;
    server_name 135.181.197.15;

    root /var/www/html;
    index index.html;

    ssl_certificate /etc/ssl/certs/nexluck-selfsigned.crt;
    ssl_certificate_key /etc/ssl/private/nexluck-selfsigned.key;
    ssl_protocols TLSv1.2 TLSv1.3;
    ssl_session_cache shared:SSL:10m;
    ssl_session_timeout 10m;

    location = /l {
        rewrite ^ /landing.html last;
    }

    location / {
        try_files $uri $uri/ =404;
    }
}
